apiVersion: apps/v1
kind: Deployment
metadata:
  name: indigoapi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: indigoapi
  template:
    metadata:
      labels:
        app: indigoapi
    spec:
      containers:
        - name: indigoapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}

          ports:
            - containerPort: {{ .Values.service.port }}

          env:
            - name: RABBITMQ__ENABLED
              value: "{{ .Values.config.rabbitmq.enabled | quote }}"
            - name: RABBITMQ__HOST
              value: "{{ .Values.config.rabbitmq.host }}"
            - name: RABBITMQ__PORT
              value: "{{ .Values.config.rabbitmq.port | quote }}"
            - name: RABBITMQ__USERNAME
              value: "{{ .Values.config.rabbitmq.username }}"
            - name: RABBITMQ__PASSWORD
              value: "{{ .Values.config.rabbitmq.password }}"

            - name: QUEUE__WORKERS
              value: "{{ .Values.config.queue.workers | quote }}"

{{- range $i, $path := .Values.config.plugins.paths }}
            - name: PLUGINS__PATHS__{{ $i }}
              value: "{{ $path }}"
{{- end }}

{{- range $i, $dest := .Values.config.rabbitmq.destinations }}
            - name: RABBITMQ__DESTINATIONS__{{ $i }}
              value: "{{ $dest }}"
{{- end }}

          resources:
{{ toYaml .Values.resources | indent 12 }}

      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}

      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}

      affinity:
{{ toYaml .Values.affinity | indent 8 }}
