apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: indigoapi
  title: indigoapi
  description: An API for small fast data analysis jobs at Diamond Light Source
spec:
  type: service
  lifecycle: experimental
  owner: group:default/data_analysis
