server:
  host: "0.0.0.0"
  port: 8000

queue:
  workers: 4

results:
  ttl_seconds: 3600 #time to live of results before deletion

cleanup:
  interval_seconds: 300 #frequency of checking for deletable results

plugins:
  paths:
    - ./plugins # local folder for plugins
  github_repos: # list of GitHub repos with analysis code

rabbitmq:
  url: "amqp://guest:guest@i15-1-rabbitmq-daq.diamond.ac.uk:5672/"
  queues:
    - analysis_jobs
    # - other_jobs
