server:
  host: "0.0.0.0"
  port: 8000

queue:
  workers: 4

results:
  ttl_seconds: 3600 #time to live of results before deletion

cleanup:
  interval_seconds: 300 #frequency of checking for deletable results

plugins:
  paths:
    - ./plugins # local folder for plugins
  github_repos: # list of GitHub repos with analysis code

rabbitmq:
  listen_on_rabbitmq: True
  host: "i15-1-rabbitmq-daq.diamond.ac.uk"
  username: "guest"
  password: "guest"
  port: 61613
  destinations:
    - "/topic/public.worker.event" #bluesky scans
    - "/topic/gda.messages.scan" # gda scans
    - "/topic/gda.messages.processing" # dawn stuff
