replicaCount: 1

image:
  repository: ghcr.io/diamondlightsource/indigoapi
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources: {}

config:
  server:
    host: "0.0.0.0"
    port: 8000

  queue:
    workers: 2

  results:
    ttl_seconds: 3600

  cleanup:
    interval_seconds: 300

  rabbitmq:
    enabled: True
    host: "ixx-rabbitmq-daq.diamond.ac.uk"
    username: "guest"
    password: "guest"
    port: 61613
    destinations:
      - "/topic/public.worker.event" #bluesky scans
      - "/topic/gda.messages.scan" # gda scans
      - "/topic/gda.messages.processing" # dawn stuff
