replicaCount: 1

image:
  repository: ghcr.io/diamondlightsource/indigoapi
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources: {}

config:
  server:
    host: "0.0.0.0"
    port: 8000

  queue:
    workers: 2

  results:
    ttl_seconds: 3600

  cleanup:
    interval_seconds: 300

  rabbitmq:
    url: "amqp://rabbitmq:15672"
    queues:
      - analysis_jobs
